In [1]:
import numpy as np
x = np.array([1,2,3,4,5])

In [2]:
print(x[-2])


4


In [3]:
x = np.arange(1,10).reshape(3,3)


In [4]:
print(x)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [6]:
v = np.delete(x,[1,2], axis = 1)
print(v)

[[1]
 [4]
 [7]]


In [7]:
w = np.append(x,[[4],[7],[10]],axis = 1)
print(w)

[[ 1  2  3  4]
 [ 4  5  6  7]
 [ 7  8  9 10]]


In [10]:
z = np.hstack((x,v))
print(z)

[[1 2 3 1]
 [4 5 6 4]
 [7 8 9 7]]


In [14]:
print("x",x)
z = np.insert(x,1,[1,4,7],axis=1)
print(z)

x [[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 1 2 3]
 [4 4 5 6]
 [7 7 8 9]]


In [15]:
# slice
x = np.arange(1,21).reshape(4,5)
print(x)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [16]:
z = x[1:4,2:5]
print(z)

[[ 8  9 10]
 [13 14 15]
 [18 19 20]]


In [17]:
z = x[1:,2:]
print(z)

[[ 8  9 10]
 [13 14 15]
 [18 19 20]]


In [18]:
z[1][2]

15

In [19]:
z[1,2]

15

In [20]:
# not copyed!!!!!!
z[1,2] = 10
print(x)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 10]
 [16 17 18 19 20]]


In [22]:
z = x[1:,2:].copy()
print("diag:",np.diag(z,-1))

diag: [13 19]


In [26]:
# boolean compare and sort

x = np.random.randint(1,11,size = (10,)).reshape(2,5)
print(x)

[[ 8  6  7 10  6]
 [ 2  5  7  7 10]]


In [29]:
print(x[(x>4) & (x<7)])

[6 6 5]


In [30]:
print(x[(x>=3)&(x<=7)])

[6 7 6 5 7 7]


In [33]:
print(x)
print(np.sort(x,axis = 0))

[[ 8  6  7 10  6]
 [ 2  5  7  7 10]]
[[ 2  5  7  7  6]
 [ 8  6  7 10 10]]


In [36]:
# elementvise operation
x = np.random.randint(1,10,size = (10,))
y = np.random.randint(1,10,size = (10,))
print(x)
print(y)
print(x+y)

[9 2 7 6 3 4 6 2 1 3]
[2 2 4 7 3 8 1 3 5 7]
[11  4 11 13  6 12  7  5  6 10]


In [37]:
# broadcasting
x = np.array([1,2,3,4])
y = np.random.randint(1,25,size=16).reshape(4,4)
print(x)
print(y)
print(x+y)

[1 2 3 4]
[[ 5  4 19  4]
 [ 5  1  3 18]
 [21  1 12  2]
 [14 22 17  2]]
[[ 6  6 22  8]
 [ 6  3  6 22]
 [22  3 15  6]
 [15 24 20  6]]


In [40]:
x = np.arange(0,4).reshape(4,1)+np.ones(4)
print(x)

[[1. 1. 1. 1.]
 [2. 2. 2. 2.]
 [3. 3. 3. 3.]
 [4. 4. 4. 4.]]


In [47]:
np.mean(x,axis=1)

array([1., 2., 3., 4.])

In [48]:
x.shape()

TypeError: 'tuple' object is not callable

In [50]:
print(np.shape(x)[1])

4


In [2]:
x = np.linspace(-15, 15, 9)

In [3]:
print(x)

[-15.   -11.25  -7.5   -3.75   0.     3.75   7.5   11.25  15.  ]


In [9]:
from scipy import stats

In [11]:
stats.kstest(x,'norm')

KstestResult(statistic=0.44435602715924361, pvalue=0.038850142705171065)

In [12]:
a = np.array([0.12, -0.83, 0.37, 0.83, -0.34, 0.27, -0.68, 0.29, 0.69,
                                  0.57, 0.39, 0.56, -0.97, -0.72, 0.26])


In [18]:
n = a.reshape(5,3).T

In [19]:
n[0]

array([ 0.12,  0.83, -0.68,  0.57, -0.97])

In [30]:
n[0].std(ddof=0),n[0].mean()

(0.69686727574194496, -0.026000000000000023)

In [29]:
stats.kstest(n[0],'norm',args=(n[0].mean(),n[0].std(ddof=0)))

KstestResult(statistic=0.22600257870428225, pvalue=0.96041495106582353)