In [1]:
import pandas as pd
import numpy as np



In [6]:
groceries

eggs        1
tomato      2
milk      Yes
butter     No
dtype: object

In [14]:
groceries = pd.Series(data=np.array([1,2,"Yes",'No']),index=['eggs','tomato','milk','butter'])

In [16]:
groceries

eggs        1
tomato      2
milk      Yes
butter     No
dtype: object

In [26]:
a = pd.Series(np.random.randn(3),['a','b','c'])
a

a   -0.104463
b   -0.788751
c    0.796710
dtype: float64

In [27]:
a[a>a.mean()]

c    0.79671
dtype: float64

In [28]:
d = {'a':1,'b':2,'c':3}

In [30]:
b = pd.Series(d)
b


a    1
b    2
c    3
dtype: int64

In [44]:
d = {'b':2.,'c':3.,'a':1.}

In [45]:
c = pd.Series(d)
c

a    1.0
b    2.0
c    3.0
dtype: float64

In [42]:
e = {1:1,2:2,3:3}

a    True
b    True
c    True
dtype: bool

In [49]:
c[1:]

b    2.0
c    3.0
dtype: float64

In [50]:
c[:-1]

a    1.0
b    2.0
dtype: float64

In [51]:
c[1:]+c[:-1]

a    NaN
b    4.0
c    NaN
dtype: float64

In [53]:
(groceries+c).dropna()

Series([], dtype: object)

In [73]:
groceries

eggs        1
tomato      2
milk      Yes
butter     No
TUTU        3
dtype: object

In [54]:
d = {'one' : pd.Series([1., 2., 3.], index=['a', 'b', 'c']),
     'two' : pd.Series([1., 2., 3., 4.], index=['a', 'b', 'd', 'c'])}
f = pd.DataFrame(d)

In [58]:
df = pd.DataFrame(d, index=['d', 'b', 'a'], columns=['two', 'three'])

In [59]:
f


one  two
a  1.0  1.0
b  2.0  2.0
c  3.0  4.0
d  NaN  3.0

In [60]:
df.index

Index(['d', 'b', 'a'], dtype='object')

In [64]:
df.columns

Index(['two', 'three'], dtype='object')

In [74]:
groceries['eggs']  = 3
groceries

eggs        3
tomato      2
milk      Yes
butter     No
TUTU        3
dtype: object

In [65]:
dir(df)

['T',
 '_AXIS_ALIASES',
 '_AXIS_IALIASES',
 '_AXIS_LEN',
 '_AXIS_NAMES',
 '_AXIS_NUMBERS',
 '_AXIS_ORDERS',
 '_AXIS_REVERSED',
 '_AXIS_SLICEMAP',
 '__abs__',
 '__add__',
 '__and__',
 '__array__',
 '__array_wrap__',
 '__bool__',
 '__bytes__',
 '__class__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dict__',
 '__dir__',
 '__div__',
 '__doc__',
 '__eq__',
 '__finalize__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattr__',
 '__getattribute__',
 '__getitem__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__imod__',
 '__imul__',
 '__init__',
 '__init_subclass__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lt__',
 '__mod__',
 '__module__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__nonzero__',
 '__or__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdiv__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__rfloordiv__',


In [69]:
nx = np.array([('t',32,150.),('tu',33,152.),('mt',32,120.)],dtype=[('name','U10'),('age','i4'),('weight','f4')])
nx[0]

('t', 32,  150.)

In [71]:
pd.DataFrame(nx,index=['t','tu','mt'])

name  age  weight
t     t   32   150.0
tu   tu   33   152.0
mt   mt   32   120.0

In [84]:
data2 = [{'a': 1, 'b': 2}, {'a': 5, 'b': 10, 'c': 20}]
da2 = pd.DataFrame(data2,index=['one','two'])

In [85]:
da2

a   b     c
one  1   2   NaN
two  5  10  20.0

In [74]:
pd.DataFrame({('a', 'b'): {('A', 'B'): 1, ('A', 'C'): 2}})

a
     b
A B  1
  C  2

In [75]:
dic = {'a':{'b':'c'},'d':{'e':'f'}}
pd.DataFrame(dic)

a    d
b    c  NaN
e  NaN    f

In [86]:
da2['d']  = da2['a'] +da2['b']
da2.pop('a')
da2

b     c   d
one   2   NaN   3
two  10  20.0  15

In [88]:
da2.insert(0,'a',[1,2])

In [89]:
da2

a   b     c   d
one  1   2   NaN   3
two  2  10  20.0  15

In [90]:
def fn(x):
    return x['a']/x['d']

In [91]:
da2.assign(e=fn)

a   b     c   d         e
one  1   2   NaN   3  0.333333
two  2  10  20.0  15  0.133333

In [92]:
da2.assign(e=lambda x:x['a']/x['d'])

a   b     c   d         e
one  1   2   NaN   3  0.333333
two  2  10  20.0  15  0.133333

In [95]:
da2.loc['one']

a    1.0
b    2.0
c    NaN
d    3.0
Name: one, dtype: float64

In [99]:
da2.iloc[1,1]

10

In [101]:
type(da2.iloc[1:])

pandas.core.frame.DataFrame

In [102]:
type(da2.iloc[1])

pandas.core.series.Series

In [107]:
da2[1:] == da2.iloc[1:]

a     b     c     d
two  True  True  True  True

In [108]:
np.random.randn(4,7)

array([[ 1.76695579,  1.31924844, -0.59971035,  0.68858265,  0.69927651,
        -0.73098075,  1.04320585],
       [ 1.0567275 ,  1.00243334, -0.46701955,  0.71647956,  0.00963394,
         1.33235382,  0.4534091 ],
       [-0.19157557, -1.42930881, -1.16540368, -0.43578096,  0.13283571,
         1.29369158, -0.85524115],
       [ 1.11856314,  0.108357  , -0.98571413,  0.35761198,  0.08296833,
         1.1714949 , -0.87540625]])

In [113]:
da2.T.dot(da2)

a      b   c      d
a   5.0   22.0 NaN   33.0
b  22.0  104.0 NaN  156.0
c   NaN    NaN NaN    NaN
d  33.0  156.0 NaN  234.0

In [114]:
da2

a   b     c   d
one  1   2   NaN   3
two  2  10  20.0  15

In [115]:
da2.info()

<class 'pandas.core.frame.DataFrame'>
Index: 2 entries, one to two
Data columns (total 4 columns):
a    2 non-null int64
b    2 non-null int64
c    1 non-null float64
d    2 non-null int64
dtypes: float64(1), int64(3)
memory usage: 160.0+ bytes


In [119]:
da2.columns

Index(['a', 'b', 'c', 'd'], dtype='object')

In [134]:
x = np.arange(4)
xx = x.reshape(4,1)
y = np.ones(5)
z = np.ones((3,4))
print(xx)
print(y)
xx+y

[[0]
 [1]
 [2]
 [3]]
[ 1.  1.  1.  1.  1.]


array([[ 1.,  1.,  1.,  1.,  1.],
       [ 2.,  2.,  2.,  2.,  2.],
       [ 3.,  3.,  3.,  3.,  3.],
       [ 4.,  4.,  4.,  4.,  4.]])

In [143]:
a = np.array([0.0, 10.0, 20.0, 30.0])
a.reshape(4,1)

array([[  0.],
       [ 10.],
       [ 20.],
       [ 30.]])

In [146]:
b=np.array([1,2,3,4])
a.reshape(4,1)*b

array([[   0.,    0.,    0.,    0.],
       [  10.,   20.,   30.,   40.],
       [  20.,   40.,   60.,   80.],
       [  30.,   60.,   90.,  120.]])

$$Bisic functionality$$

In [76]:
dict([('A', [1, 2, 3]), ('B', [4, 5, 6])])

{'A': [1, 2, 3], 'B': [4, 5, 6]}

In [120]:
da2

a   b     c   d
one  1   2   NaN   3
two  2  10  20.0  15

In [130]:
da2.drop('one',axis=0)

a   b     c   d
two  2  10  20.0  15

In [131]:
da2.sum(axis=0)

a     3.0
b    12.0
c    20.0
d    18.0
dtype: float64

In [129]:
da2.sum(axis=1)

one     6.0
two    47.0
dtype: float64

In [132]:
da2

a   b     c   d
one  1   2   NaN   3
two  2  10  20.0  15

In [75]:
groceries.drop('eggs',inplace = True)
groceries

tomato      2
milk      Yes
butter     No
TUTU        3
dtype: object

In [147]:
ser = pd.Series(np.random.randn(100))

In [148]:
ser.head(6)

0   -0.419233
1   -2.378026
2   -1.238593
3    0.435211
4    0.061841
5   -0.872237
dtype: float64

In [154]:
df.columns=['a','b']
df.index

Index(['d', 'b', 'a'], dtype='object')

In [156]:
df
df['b'] = [1,2,3]

In [158]:
df['c'] = [4,5,6]
df.index=['one','two','three']

In [161]:
df

a  b  c
one    3.0  1  4
two    2.0  2  5
three  1.0  3  6

In [167]:
(df>=2).all(axis=0)

a    False
b    False
c     True
dtype: bool

In [171]:
arr = np.random.randn(8)
print(arr)
p = pd.cut(arr,4)
p


[ 0.75595695  1.27797134  2.26521378 -0.59584949 -0.29707283  0.95764568
 -0.2936      1.28889384]


[(0.119, 0.835], (0.835, 1.55], (1.55, 2.265], (-0.599, 0.119], (-0.599, 0.119], (0.835, 1.55], (-0.599, 0.119], (0.835, 1.55]]
Categories (4, interval[float64]): [(-0.599, 0.119] < (0.119, 0.835] < (0.835, 1.55] < (1.55, 2.265]]

In [172]:
def subtract_and_divide(x, sub, divide=1):
    return (x - sub) / divide

In [179]:
df.apply(subtract_and_divide,args=(2,2))

a    b    c
one    0.5 -0.5  1.0
two    0.0  0.0  1.5
three -0.5  0.5  2.0

In [177]:
df

a  b  c
one    3.0  1  4
two    2.0  2  5
three  1.0  3  6

In [180]:
tsdf = pd.DataFrame(np.random.randn(10, 3), columns=['A', 'B', 'C'],index=pd.date_range('1/1/2000', periods=10))

In [183]:
tsdf

A         B         C
2000-01-01 -0.697172 -1.607952 -2.463080
2000-01-02 -0.331190 -1.094282 -0.750183
2000-01-03  0.463573 -0.035207  0.786007
2000-01-04 -0.591350  0.208392  0.829813
2000-01-05  1.533418  0.217475  0.813125
2000-01-06  1.012300  0.818504  0.054778
2000-01-07  0.146117  0.727021 -0.463365
2000-01-08  1.060989  0.973087 -0.072522
2000-01-09  1.202007  1.792198 -0.607850
2000-01-10 -0.924078 -1.307026  0.611637

In [182]:
tsdf.agg(np.sum)

A    2.874614
B    0.692211
C   -1.261639
dtype: float64

In [185]:
tsdf.A.agg('sum')

2.874614341329631

In [190]:
df4 = pd.DataFrame([['aaaa','bb'],['ceeed','dffffff']],index=['one','two'],columns=['aa','bb'])

In [191]:
f = lambda x:len(str(x))
df4['aa'].map(f)

one    4
two    5
Name: aa, dtype: int64

In [193]:
df4.applymap(f)

aa  bb
one   4   2
two   5   7

In [194]:
s = pd.Series(['six','severn','six','severn'],index=['a','b','c','d'])
t = pd.Series([6,7],index=['six','severn'])
print(s,t)
s.map(t)

a       six
b    severn
c       six
d    severn
dtype: object six       6
severn    7
dtype: int64


a    6
b    7
c    6
d    7
dtype: int64

In [201]:
df4

aa       bb
two   aaaa       bb
one  ceeed  dffffff

In [204]:
df4.index=['one','two']

In [205]:
df4

aa       bb
one   aaaa       bb
two  ceeed  dffffff

In [208]:
df4.reindex(index=['two','one'])

aa       bb
two  ceeed  dffffff
one   aaaa       bb

In [209]:
df4

aa       bb
one   aaaa       bb
two  ceeed  dffffff

In [210]:
df5 = pd.DataFrame(np.random.randn(3,4),columns=['a','b','c','d'],index=['one','two','three'])

In [211]:
df6 = pd.DataFrame(np.random.randn(3,4),columns=['a','b','c','d'],index=['three','two','one'])

In [212]:
df5

a         b         c         d
one    1.175378 -0.788867  1.142768 -0.246072
two   -1.211822  0.303453  0.031464  1.269194
three  0.003726 -0.620267  0.404228 -0.461123

In [213]:
df6

a         b         c         d
three  0.356965 -1.131993  0.472853 -1.826821
two   -0.206705  1.025919  0.575164 -0.145040
one   -0.232218 -0.335702  0.870188  0.342276

In [214]:
df6.reindex_like(df5)

a         b         c         d
one   -0.232218 -0.335702  0.870188  0.342276
two   -0.206705  1.025919  0.575164 -0.145040
three  0.356965 -1.131993  0.472853 -1.826821

In [234]:
df6

a         b         c         d
three  0.356965 -1.131993  0.472853 -1.826821
two   -0.206705  1.025919  0.575164 -0.145040
one   -0.232218 -0.335702  0.870188  0.342276

In [237]:
df6.info()

<class 'pandas.core.frame.DataFrame'>
Index: 3 entries, three to one
Data columns (total 4 columns):
a    3 non-null float64
b    3 non-null float64
c    3 non-null float64
d    3 non-null float64
dtypes: float64(4)
memory usage: 200.0+ bytes


In [239]:
df6.rename({'three':'3','two':'2','one':'1'},axis=0)

a         b         c         d
3  0.356965 -1.131993  0.472853 -1.826821
2 -0.206705  1.025919  0.575164 -0.145040
1 -0.232218 -0.335702  0.870188  0.342276

In [240]:
df6

a         b         c         d
three  0.356965 -1.131993  0.472853 -1.826821
two   -0.206705  1.025919  0.575164 -0.145040
one   -0.232218 -0.335702  0.870188  0.342276

In [236]:
df6.mode(axis=0)

a         b         c         d
0 -0.232218 -1.131993  0.472853 -1.826821
1 -0.206705 -0.335702  0.575164 -0.145040
2  0.356965  1.025919  0.870188  0.342276

In [224]:
for name,col in df6.iteritems():
    print(name)
    print(col)

a
three    0.356965
two     -0.206705
one     -0.232218
Name: a, dtype: float64
b
three   -1.131993
two      1.025919
one     -0.335702
Name: b, dtype: float64
c
three    0.472853
two      0.575164
one      0.870188
Name: c, dtype: float64
d
three   -1.826821
two     -0.145040
one      0.342276
Name: d, dtype: float64


In [215]:
df6.align(df5,join='inner')

(              a         b         c         d
 three  0.356965 -1.131993  0.472853 -1.826821
 two   -0.206705  1.025919  0.575164 -0.145040
 one   -0.232218 -0.335702  0.870188  0.342276,
               a         b         c         d
 three  0.003726 -0.620267  0.404228 -0.461123
 two   -1.211822  0.303453  0.031464  1.269194
 one    1.175378 -0.788867  1.142768 -0.246072)

In [216]:
s = pd.Series(np.random.randn(5), index=['a', 'b', 'c', 'd', 'e'])
s1 = s[:4]
s2 = s[1:]
s1

a   -2.289670
b    1.344180
c    0.205427
d    1.148270
dtype: float64

In [217]:
s2

b    1.344180
c    0.205427
d    1.148270
e    2.933659
dtype: float64

In [220]:
s2.rename({'b':'bee'})

bee    1.344180
c      0.205427
d      1.148270
e      2.933659
dtype: float64

In [221]:
s2.rename('tutu')

b    1.344180
c    0.205427
d    1.148270
e    2.933659
Name: tutu, dtype: float64

In [222]:
for a in s2:
    print(a)

1.344179583434981
0.20542672811544088
1.1482704097139451
2.933658769109078


In [223]:
for b in df6:
    print(b)

a
b
c
d


In [231]:
from collections import namedtuple
nt = namedtuple('tutu','x y')
n1 = nt(1,2)
n1.x

1

In [245]:
df7 = pd.Series(pd.date_range('20130101 09:10:12',periods=10))

In [246]:
df7

0   2013-01-01 09:10:12
1   2013-01-02 09:10:12
2   2013-01-03 09:10:12
3   2013-01-04 09:10:12
4   2013-01-05 09:10:12
5   2013-01-06 09:10:12
6   2013-01-07 09:10:12
7   2013-01-08 09:10:12
8   2013-01-09 09:10:12
9   2013-01-10 09:10:12
dtype: datetime64[ns]

In [247]:
df7.dt.weekday

0    1
1    2
2    3
3    4
4    5
5    6
6    0
7    1
8    2
9    3
dtype: int64

In [249]:
df7[df7.dt.weekday==2]

1   2013-01-02 09:10:12
8   2013-01-09 09:10:12
dtype: datetime64[ns]

In [252]:
s1 = pd.Series(np.random.randn(15))
s1[2:5]=np.nan

In [253]:
s1

0    -0.013476
1     1.147843
2          NaN
3          NaN
4          NaN
5    -0.287972
6    -1.505737
7    -0.327882
8    -0.157121
9    -1.035795
10    0.329331
11   -0.232199
12    0.763678
13   -0.597806
14    0.933935
dtype: float64

In [259]:
s1.sort_values(na_position='first',ascending=False)

2          NaN
3          NaN
4          NaN
1     1.147843
14    0.933935
12    0.763678
10    0.329331
0    -0.013476
8    -0.157121
11   -0.232199
5    -0.287972
7    -0.327882
13   -0.597806
9    -1.035795
6    -1.505737
dtype: float64

In [262]:
tf = df7
df6.sort_values(by=['a','c'])

a         b         c         d
one   -0.232218 -0.335702  0.870188  0.342276
two   -0.206705  1.025919  0.575164 -0.145040
three  0.356965 -1.131993  0.472853 -1.826821

In [269]:
(df6>0).select_dtypes(include=[bool])

a      b     c      d
three   True  False  True  False
two    False   True  True  False
one    False  False  True   True

In [267]:
s[s>0]

b    1.344180
c    0.205427
d    1.148270
e    2.933659
dtype: float64

In [270]:
s2 = pd.Series(['A', 'B', 'C', 'Aaba', 'Baca', np.nan, 'CABA', 'dog', 'cat'])

In [272]:
s2.str.upper()

0       A
1       B
2       C
3    AABA
4    BACA
5     NaN
6    CABA
7     DOG
8     CAT
dtype: object

In [275]:
st1 = pd.Series(['a_b_c','d_e_f','h_g_i'])

In [277]:
st1.str.split('_',expand=True)

0  1  2
0  a  b  c
1  d  e  f
2  h  g  i

In [278]:
st1.str.split('_',expand=True,n=1)

0    1
0  a  b_c
1  d  e_f
2  h  g_i

In [280]:
st1.str.cat()

'a_b_cd_e_fh_g_i'

In [282]:
st1[3]=np.nan

In [284]:
st1.str.cat(na_rep='%%')

'a_b_cd_e_fh_g_i%%'

In [285]:
st1

0    a_b_c
1    d_e_f
2    h_g_i
3      NaN
dtype: object

In [288]:
st2 = st1.str.split('_',expand=True)[1]

In [295]:
st2

0       b
1       e
2       g
3    None
Name: 1, dtype: object

In [290]:
st3 = st1.str.split('_',expand=True)[2]

In [293]:
pd.concat([st2,st3],axis=1)

1     2
0     b     c
1     e     f
2     g     i
3  None  None

In [303]:
pd.Index(st3.values)

Index(['c', 'f', 'i', None], dtype='object')

In [307]:
st1.str[3]

0      _
1      _
2      _
3    NaN
dtype: object

In [308]:
st4 = pd.Series(['a', 'a|b', np.nan, 'a|c'])

In [309]:
st4

0      a
1    a|b
2    NaN
3    a|c
dtype: object

In [311]:
st4.str.get_dummies(sep='|')

a  b  c
0  1  0  0
1  1  1  0
2  0  0  0
3  1  0  1

In [3]:
df8 = pd.DataFrame({'a':np.random.randn(4),'b':np.random.randn(4),'c':np.random.randn(4)},index=['A','B','C','D'])

In [4]:
df8

a         b         c
A -0.052388  1.272358 -0.721022
B  1.150405  0.780760  0.627815
C  1.877816  0.450438 -0.665685
D -0.256418 -1.717103 -0.421283

In [5]:
row = df8.iloc[1]

In [6]:
row

a    1.150405
b    0.780760
c    0.627815
Name: B, dtype: float64

In [9]:
df8.sub(row,axis=0)

a   b   c
A NaN NaN NaN
B NaN NaN NaN
C NaN NaN NaN
D NaN NaN NaN
a NaN NaN NaN
b NaN NaN NaN
c NaN NaN NaN

In [12]:
type(df8.align(df8))

tuple

In [16]:
type(pd.Series(['a1', 'b2', 'c3']).str.extract('(?P<letter>[ab])(?P<digit>\d)', expand=False))

pandas.core.frame.DataFrame

In [17]:
s = pd.Series(["a1", "b2", "c3"], ["A11", "B22", "C33"])
s.index

Index(['A11', 'B22', 'C33'], dtype='object')

In [19]:
pd.describe_option()

compute.use_bottleneck : bool
    Use the bottleneck library to accelerate if it is installed,
    the default is True
    Valid values: False,True
    [default: True] [currently: True]

compute.use_numexpr : bool
    Use the numexpr library to accelerate computation if it is installed,
    the default is True
    Valid values: False,True
    [default: True] [currently: True]

display.chop_threshold : float or None
    if set to a float value, all float values smaller then the given threshold
    will be displayed as exactly 0 by repr and friends.
    [default: None] [currently: None]

display.colheader_justify : 'left'/'right'
    Controls the justification of column headers. used by DataFrameFormatter.
    [default: right] [currently: right]

display.column_space No description available.
    [default: 12] [currently: 12]

display.date_dayfirst : boolean
    When True, prints and parses dates with the day first, eg 20/01/2005
    [default: False] [currently: False]

display.date_year

In [2]:
dates = pd.date_range('1/1/2000', periods=8)
df = pd.DataFrame(np.random.randn(8, 4), index=dates, columns=['A', 'B', 'C', 'D'])

In [3]:
panel = pd.Panel({'one':df,'two':df-df.mean()})

In [4]:
df[['B','A']]=df[['A','B']]

In [5]:
df

A         B         C         D
2000-01-01 -0.539914 -1.883391  1.190312  1.553649
2000-01-02 -1.440367  0.185816 -0.116872 -0.792835
2000-01-03  0.161829  0.575417  0.775878  0.045185
2000-01-04 -1.574765 -1.330214  0.939042  1.287767
2000-01-05  0.262598  0.415353  1.552895  0.373992
2000-01-06  0.792195 -0.354154  0.312348  0.420638
2000-01-07  0.753429  0.373884 -0.490253 -1.051247
2000-01-08 -1.244096 -0.535286  0.517245 -0.804359

In [6]:
df[['B','A']]=df[['A','B']]
df

A         B         C         D
2000-01-01 -1.883391 -0.539914  1.190312  1.553649
2000-01-02  0.185816 -1.440367 -0.116872 -0.792835
2000-01-03  0.575417  0.161829  0.775878  0.045185
2000-01-04 -1.330214 -1.574765  0.939042  1.287767
2000-01-05  0.415353  0.262598  1.552895  0.373992
2000-01-06 -0.354154  0.792195  0.312348  0.420638
2000-01-07  0.373884  0.753429 -0.490253 -1.051247
2000-01-08 -0.535286 -1.244096  0.517245 -0.804359

In [7]:
df.loc[:,['B', 'A']]

B         A
2000-01-01 -0.539914 -1.883391
2000-01-02 -1.440367  0.185816
2000-01-03  0.161829  0.575417
2000-01-04 -1.574765 -1.330214
2000-01-05  0.262598  0.415353
2000-01-06  0.792195 -0.354154
2000-01-07  0.753429  0.373884
2000-01-08 -1.244096 -0.535286

In [8]:
df[['A','B']]

A         B
2000-01-01 -1.883391 -0.539914
2000-01-02  0.185816 -1.440367
2000-01-03  0.575417  0.161829
2000-01-04 -1.330214 -1.574765
2000-01-05  0.415353  0.262598
2000-01-06 -0.354154  0.792195
2000-01-07  0.373884  0.753429
2000-01-08 -0.535286 -1.244096

In [23]:
df.loc[:,['A','B']]

A         B
2000-01-01 -1.883391 -0.539914
2000-01-02  0.185816 -1.440367
2000-01-03  0.575417  0.161829
2000-01-04 -1.330214 -1.574765
2000-01-05  0.415353  0.262598
2000-01-06 -0.354154  0.792195
2000-01-07  0.373884  0.753429
2000-01-08 -0.535286 -1.244096

In [33]:
df[['A', 'B']] = df[['B','A']].values

In [35]:
df.values

array([[-0.53991434, -1.88339084,  1.19031199,  1.55364914],
       [-1.44036663,  0.18581616, -0.11687216, -0.79283491],
       [ 0.16182858,  0.57541727,  0.77587753,  0.04518483],
       [-1.57476474, -1.33021371,  0.93904248,  1.28776715],
       [ 0.26259777,  0.415353  ,  1.55289536,  0.37399209],
       [ 0.7921953 , -0.35415383,  0.31234848,  0.42063823],
       [ 0.75342948,  0.3738836 , -0.49025261, -1.0512467 ],
       [-1.24409554, -0.53528627,  0.51724498, -0.80435913]])

In [36]:
df.index=[i for i in range(8)]

In [37]:
df

A         B         C         D
0 -0.539914 -1.883391  1.190312  1.553649
1 -1.440367  0.185816 -0.116872 -0.792835
2  0.161829  0.575417  0.775878  0.045185
3 -1.574765 -1.330214  0.939042  1.287767
4  0.262598  0.415353  1.552895  0.373992
5  0.792195 -0.354154  0.312348  0.420638
6  0.753429  0.373884 -0.490253 -1.051247
7 -1.244096 -0.535286  0.517245 -0.804359

In [38]:
df.loc[1:4]

A         B         C         D
1 -1.440367  0.185816 -0.116872 -0.792835
2  0.161829  0.575417  0.775878  0.045185
3 -1.574765 -1.330214  0.939042  1.287767
4  0.262598  0.415353  1.552895  0.373992

In [39]:
df.iloc[1:4]

A         B         C         D
1 -1.440367  0.185816 -0.116872 -0.792835
2  0.161829  0.575417  0.775878  0.045185
3 -1.574765 -1.330214  0.939042  1.287767

In [41]:
df[df.A>0]

A         B         C         D
2  0.161829  0.575417  0.775878  0.045185
4  0.262598  0.415353  1.552895  0.373992
5  0.792195 -0.354154  0.312348  0.420638
6  0.753429  0.373884 -0.490253 -1.051247

In [47]:
df.sample(n=2)

A         B         C         D
4  0.262598  0.415353  1.552895  0.373992
3 -1.574765 -1.330214  0.939042  1.287767

In [50]:
df

A         B         C         D
0 -0.539914 -1.883391  1.190312  1.553649
1 -1.440367  0.185816 -0.116872 -0.792835
2  0.161829  0.575417  0.775878  0.045185
3 -1.574765 -1.330214  0.939042  1.287767
4  0.262598  0.415353  1.552895  0.373992
5  0.792195 -0.354154  0.312348  0.420638
6  0.753429  0.373884 -0.490253 -1.051247
7 -1.244096 -0.535286  0.517245 -0.804359

In [51]:
df.at[1,'A']

-1.4403666251678726

In [52]:
df2 = pd.DataFrame({'a' : ['one', 'one', 'two', 'three', 'two', 'one', 'six'],
                   'b' : ['x', 'y', 'y', 'x', 'y', 'x', 'x'],
                    'c' : np.random.randn(7)})

In [57]:
df2['a'].map(lambda x: x.startswith('t'))

0    False
1    False
2     True
3     True
4     True
5    False
6    False
Name: a, dtype: bool

In [3]:
df

A         B         C         D
2000-01-01 -1.532624 -1.258853 -0.255231 -1.340678
2000-01-02 -0.043785 -1.059949 -0.916669  0.175472
2000-01-03 -1.270354  1.712327  1.173104 -0.849084
2000-01-04  0.328163 -0.316757  0.006914  0.799224
2000-01-05  1.665272 -0.098385 -0.018129 -0.197813
2000-01-06 -0.008312 -0.094300 -0.181805  1.746426
2000-01-07 -1.209941 -0.509143 -0.767566  1.610671
2000-01-08  1.044843  0.747775 -0.310905 -0.439182

In [5]:
df.where(df>0,1)

A         B         C         D
2000-01-01  1.000000  1.000000  1.000000  1.000000
2000-01-02  1.000000  1.000000  1.000000  0.175472
2000-01-03  1.000000  1.712327  1.173104  1.000000
2000-01-04  0.328163  1.000000  0.006914  0.799224
2000-01-05  1.665272  1.000000  1.000000  1.000000
2000-01-06  1.000000  1.000000  1.000000  1.746426
2000-01-07  1.000000  1.000000  1.000000  1.610671
2000-01-08  1.044843  0.747775  1.000000  1.000000

In [6]:
df.where(df < 0, -df) == np.where(df < 0, df, -df)

A     B     C     D
2000-01-01  True  True  True  True
2000-01-02  True  True  True  True
2000-01-03  True  True  True  True
2000-01-04  True  True  True  True
2000-01-05  True  True  True  True
2000-01-06  True  True  True  True
2000-01-07  True  True  True  True
2000-01-08  True  True  True  True

In [7]:
df[1:4]

A         B         C         D
2000-01-02 -0.043785 -1.059949 -0.916669  0.175472
2000-01-03 -1.270354  1.712327  1.173104 -0.849084
2000-01-04  0.328163 -0.316757  0.006914  0.799224

In [13]:
df[['A','B']]

A         B
2000-01-01 -1.532624 -1.258853
2000-01-02 -0.043785 -1.059949
2000-01-03 -1.270354  1.712327
2000-01-04  0.328163 -0.316757
2000-01-05  1.665272 -0.098385
2000-01-06 -0.008312 -0.094300
2000-01-07 -1.209941 -0.509143
2000-01-08  1.044843  0.747775

In [23]:
df[df['A']>1]

A         B         C         D
2000-01-05  1.665272 -0.098385 -0.018129 -0.197813
2000-01-08  1.044843  0.747775 -0.310905 -0.439182

In [24]:
df1= pd.DataFrame({'a': list('aabbccddeeff'), 'b': list('aaaabbbbcccc'),
                   'c': np.random.randint(5, size=12),
                 'd': np.random.randint(9, size=12)})

In [25]:
df1.query('a in b')

a  b  c  d
0  a  a  4  3
1  a  a  0  1
2  b  a  2  4
3  b  a  3  2
4  c  b  1  8
5  c  b  1  4

In [29]:
df1[df1['a'].isin(df1['b'])]

a  b  c  d
0  a  a  4  3
1  a  a  0  1
2  b  a  2  4
3  b  a  3  2
4  c  b  1  8
5  c  b  1  4

In [33]:
a = 3
b=1
c =1 
d =1

In [35]:
df1.query('b in ["a","b"]')

a  b  c  d
0  a  a  4  3
1  a  a  0  1
2  b  a  2  4
3  b  a  3  2
4  c  b  1  8
5  c  b  1  4
6  d  b  1  6
7  d  b  4  0

In [36]:
df1.query('b ==["a","b"]')

a  b  c  d
0  a  a  4  3
1  a  a  0  1
2  b  a  2  4
3  b  a  3  2
4  c  b  1  8
5  c  b  1  4
6  d  b  1  6
7  d  b  4  0

In [47]:
df1.c = df1.c.astype(bool)

In [49]:
df1.query('not c')

a  b      c  d
1   a  a  False  1
10  f  c  False  7

In [50]:
df2 = pd.DataFrame({'a': ['one', 'one', 'two', 'two', 'two', 'three', 'four'],
                    'b': ['x', 'y', 'x', 'y', 'x', 'x', 'x'],
                    'c': np.random.randn(7)})

In [51]:
df2.duplicated('a')

0    False
1     True
2    False
3     True
4     True
5    False
6    False
dtype: bool

In [53]:
df2.drop_duplicates('a',keep='first')

a  b         c
0    one  x  1.530001
2    two  x -0.105380
5  three  x  1.396053
6   four  x  1.630809

In [54]:
df2.drop_duplicates(df2.columns)

a  b         c
0    one  x  1.530001
1    one  y  0.876366
2    two  x -0.105380
3    two  y -0.953622
4    two  x  0.554484
5  three  x  1.396053
6   four  x  1.630809

In [55]:
df3 = pd.DataFrame({'a': np.arange(6),
                    'b': np.random.randn(6)},
                 index=['a', 'a', 'b', 'c', 'b', 'a'])

In [59]:
df3[~df3.index.duplicated()]

a         b
a  0 -1.022995
b  2 -0.979081
c  3 -1.445170

In [61]:
df3.duplicated()

a    False
a    False
b    False
c    False
b    False
a    False
dtype: bool

In [63]:
df3

a         b
a  0 -1.022995
a  1 -1.271400
b  2 -0.979081
c  3 -1.445170
b  4  1.047075
a  5 -0.877398

In [64]:
df3.get('a')

a    0
a    1
b    2
c    3
b    4
a    5
Name: a, dtype: int64

In [67]:
df3.lookup(['a','b'],['a','b'])

array([array([0, 1, 5]), array([-0.97908114,  1.0470753 ])], dtype=object)

In [68]:
dflookup = pd.DataFrame(np.random.rand(20,4), columns = ['A','B','C','D'])

In [69]:
dflookup

A         B         C         D
0   0.856499  0.584390  0.842063  0.453973
1   0.886702  0.588840  0.165512  0.436237
2   0.081994  0.610995  0.975750  0.977457
3   0.339068  0.162463  0.365779  0.469174
4   0.097630  0.742304  0.202450  0.746210
5   0.154931  0.480796  0.500719  0.165899
6   0.409810  0.877171  0.857760  0.220439
7   0.230845  0.512387  0.792074  0.004951
8   0.094970  0.327292  0.968866  0.503204
9   0.957650  0.424908  0.904079  0.594688
10  0.646835  0.192328  0.804654  0.797981
11  0.629976  0.279699  0.611107  0.653320
12  0.960668  0.950673  0.346433  0.954208
13  0.835565  0.343413  0.209688  0.597594
14  0.653082  0.061349  0.633032  0.636647
15  0.542729  0.694251  0.051635  0.610744
16  0.649616  0.584951  0.895720  0.768420
17  0.273771  0.556943  0.990805  0.291794
18  0.315626  0.681380  0.462986  0.413891
19  0.374989  0.121782  0.639032  0.688958

In [70]:
dflookup.lookup(list(range(0,10,2)), ['B','C','A','B','D'])

array([ 0.58438996,  0.97574983,  0.09763006,  0.87717081,  0.50320448])

In [71]:
index = pd.MultiIndex.from_product([range(3), ['one', 'two']], names=['first', 'second'])

In [72]:
index

MultiIndex(levels=[[0, 1, 2], ['one', 'two']],
           labels=[[0, 0, 1, 1, 2, 2], [0, 1, 0, 1, 0, 1]],
           names=['first', 'second'])

In [73]:
a = pd.Index(['c', 'b', 'a'])

In [74]:
b = pd.Index(['c', 'e', 'd'])

In [75]:
a^b

Index(['a', 'b', 'd', 'e'], dtype='object')

In [76]:
a|b

Index(['a', 'b', 'c', 'd', 'e'], dtype='object')

In [77]:
a&b

Index(['c'], dtype='object')

In [78]:
df3

a         b
a  0 -1.022995
a  1 -1.271400
b  2 -0.979081
c  3 -1.445170
b  4  1.047075
a  5 -0.877398

In [79]:
df3.set_index(['a'])

b
a          
0 -1.022995
1 -1.271400
2 -0.979081
3 -1.445170
4  1.047075
5 -0.877398

In [80]:
df3.set_index(['a'],append=True)

b
  a          
a 0 -1.022995
  1 -1.271400
b 2 -0.979081
c 3 -1.445170
b 4  1.047075
a 5 -0.877398

In [81]:
df3

a         b
a  0 -1.022995
a  1 -1.271400
b  2 -0.979081
c  3 -1.445170
b  4  1.047075
a  5 -0.877398

In [94]:
t = df3.reset_index()
t.rename(columns={'index':'c'})

c  a         b
0  a  0 -1.022995
1  a  1 -1.271400
2  b  2 -0.979081
3  c  3 -1.445170
4  b  4  1.047075
5  a  5 -0.877398

In [91]:
t

index  a         b
0     a  0 -1.022995
1     a  1 -1.271400
2     b  2 -0.979081
3     c  3 -1.445170
4     b  4  1.047075
5     a  5 -0.877398

In [95]:
dfmi=pd.DataFrame([list('abcd'),list('efgh'),list('ijkl'),list('mnop')],columns=pd.MultiIndex.from_product([('a','b'),('one','two')]))

In [96]:
dfmi

a       b    
  one two one two
0   a   b   c   d
1   e   f   g   h
2   i   j   k   l
3   m   n   o   p

In [97]:
dfmi.loc[:,('a','one')]

0    a
1    e
2    i
3    m
Name: (a, one), dtype: object

In [98]:
dfmi['a']['one']=[i for i in'efgh']

/Users/fufeidu/Library/Python/3.6/lib/python/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.


In [99]:
dfmi

a       b    
  one two one two
0   e   b   c   d
1   f   f   g   h
2   g   j   k   l
3   h   n   o   p

In [100]:
dfmi.loc

<center>Should avoid to use df[0]['col']</center>